services:
  db:
    image: postgres:13
    container_name: workout_postgres
    restart: always
    environment:
      POSTGRES_USER: workout
      POSTGRES_PASSWORD: workout 
      POSTGRES_DB: workoutdb
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata

volumes:
  db_data: